### 
GET http://localhost:3000/api/sponsors/allAthletes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NSwiZXhwaXJlZF9hdCI6MTYzMjA0NzMxMiwiY3JlYXRlZF9hdCI6MTYzMjA0MzcxMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjA0MzcxMn0.JN-ojCFHN8MAPC9QfdkCzmgiPGIcBgziiu3UWYaqjFI

### 
GET http://localhost:3000/api/sponsors/athletes/51
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NSwiZXhwaXJlZF9hdCI6MTYzMjA0NzMxMiwiY3JlYXRlZF9hdCI6MTYzMjA0MzcxMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjA0MzcxMn0.JN-ojCFHN8MAPC9QfdkCzmgiPGIcBgziiu3UWYaqjFI


###
GET http://localhost:3000/api/sponsors/athletesPercentage
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE2NzkxNSwiY3JlYXRlZF9hdCI6MTYzMjE2NDMxNSwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE2NDMxNX0.ZlMczW4ctZ1wtoRflM4hH9yQ6gJ6EFXyZVg799FQWBo

###
GET http://localhost:3000/api/sponsors/athletesLimitdate
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE2NzkxNSwiY3JlYXRlZF9hdCI6MTYzMjE2NDMxNSwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE2NDMxNX0.ZlMczW4ctZ1wtoRflM4hH9yQ6gJ6EFXyZVg799FQWBo


### 
GET http://localhost:3000/api/athletes/allOffers/49
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MSwiZXhwaXJlZF9hdCI6MTYzMjA1MDgwMiwiY3JlYXRlZF9hdCI6MTYzMjA0NzIwMiwidXNlcl9yb2xlIjoiQSIsImlhdCI6MTYzMjA0NzIwMn0.BdlGRLinJqOqVjNKQ5ylpM_eUkpYQkxqbl7mRw730gw


### 
GET http://localhost:3000/api/athletes/offers/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHBpcmVkX2F0IjoxNjMxNTQ0MDI5LCJjcmVhdGVkX2F0IjoxNjMxNTQzNzI5LCJpYXQiOjE2MzE1NDM3Mjl9.lq-P9mRgcbdDG8ZzJFLfAF-I5V_rty4a8SonVtPUB3I


### 
GET http://localhost:3000/api/athletes/rejectedOffers/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NiwiZXhwaXJlZF9hdCI6MTYzMTg3OTc1NSwiY3JlYXRlZF9hdCI6MTYzMTg3NjE1NSwidXNlcl9yb2xlIjoiQSIsImlhdCI6MTYzMTg3NjE1NX0.TAO9lQ5zbEbvZq1aWsQ868IHp462hK8RYzvqAe7JA_Y


### 
GET http://localhost:3000/api/athletes/holdOffers/2
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkX2F0IjoxNjMxNjQyMjMxLCJjcmVhdGVkX2F0IjoxNjMxNjM4NjMxLCJpYXQiOjE2MzE2Mzg2MzF9.6DccrZ8RsKlB6z-Mve6FJSeORt5aH0x1YC9cRCCYYSE


### 
GET http://localhost:3000/api/athletes/mysponsors/3
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkX2F0IjoxNjMxNjQyMjMxLCJjcmVhdGVkX2F0IjoxNjMxNjM4NjMxLCJpYXQiOjE2MzE2Mzg2MzF9.6DccrZ8RsKlB6z-Mve6FJSeORt5aH0x1YC9cRCCYYSE


### 
PUT http://localhost:3000/api/athletes/profile/52
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MywiZXhwaXJlZF9hdCI6MTYzMjA5MzMyNCwiY3JlYXRlZF9hdCI6MTYzMjA4OTcyNCwidXNlcl9yb2xlIjoiQSIsImlhdCI6MTYzMjA4OTcyNH0.mBzZY-WNuec8XnJzmK4vWXCvkj1h_2EIT8F5epFrVw8
Content-Type: application/json

{
    "name": "Sijjjka",
    "surname": "Hernaiz",
    "age": 12,
    "photo": "fotodelamásguapa",
    "sport": "pádel",
    "country": "País Valencià", 
    "quantitydemand": 1000,
    "percentage": 100,
    "limitdate": "2022-02-02",
    "grafic": "ahksuhas",
    "followers": 9000,
    "email": "rsica@gmail.com"
}


###
PUT http://localhost:3000/api/athletes/acceptOffer
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MywiZXhwaXJlZF9hdCI6MTYzMjA5MzM4NCwiY3JlYXRlZF9hdCI6MTYzMjA4OTc4NCwidXNlcl9yb2xlIjoiQSIsImlhdCI6MTYzMjA4OTc4NH0.1nQAyQdiNfF09LPwLnjMdNEU-DOVjX8mJ8z36kYQ7Ko

{
    "id": 44
}


### 
POST http://localhost:3000/api/users/register/athlete
Content-Type: application/json

{
    "email": "rassaeekkess@gmail.com",
    "password": "aaaY9*",
    "name": "aaaaa",
    "surname": "Jisaslg",
    "age": 20
}


### 

POST http://localhost:3000/api/users/register/sponsor
Content-Type: application/json

{
    "email": "roewtto@gmail.com",
    "password": "aaaY9*",
    "company": "RORO si"
}


### 
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "adidas@gmail.com",
    "password": "Admin123!"
}


### 
PUT http://localhost:3000/api/users/offers
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJleHBpcmVkX2F0IjoxNjMxNDcyNTY4LCJjcmVhdGVkX2F0IjoxNjMxNDcyMjY4LCJpYXQiOjE2MzE0NzIyNjh9.
Content-Type: application/json

{
    "id": "6",
    "fk_athletes": "1",
    "fk_sponsors": "4",
    "participations": "100",
    "status": "1"
}


### 
PUT http://localhost:3000/api/athletes/profile/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NiwiZXhwaXJlZF9hdCI6MTYzMTg3NTYyMywiY3JlYXRlZF9hdCI6MTYzMTg3MjAyMywidXNlcl9yb2xlIjoiQSIsImlhdCI6MTYzMTg3MjAyM30.USDvxncuV6O4YPtPx_o15ei8Bo6oX5Ppj2sKaMpLr1g
Content-Type: application/json

{
    "name": "Sica",
    "surname": "Estevan",
    "age": 819,
    "photo": "jahskjahsas",
    "sport": "Ski",
    "country": "Norway",
    "quantifydemand": 1000,
    "percentage": 0,
    "limitdate": "2021-11-21",
    "graphic": "jasijailjs",
    "followers": 130
}


###
GET http://localhost:3000/api/sponsors/athletes/filterCountry/France
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE1NDMyMiwiY3JlYXRlZF9hdCI6MTYzMjE1MDcyMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE1MDcyMn0.49fdCbK2NwWcsLekEnZlTsImxV2lWkpk74URnUEhV28

###
GET http://localhost:3000/api/sponsors/athletes/filterSport/Basket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE1NDMyMiwiY3JlYXRlZF9hdCI6MTYzMjE1MDcyMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE1MDcyMn0.49fdCbK2NwWcsLekEnZlTsImxV2lWkpk74URnUEhV28


###
GET http://localhost:3000/api/sponsors/athletes/invertibles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE1NDMyMiwiY3JlYXRlZF9hdCI6MTYzMjE1MDcyMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE1MDcyMn0.49fdCbK2NwWcsLekEnZlTsImxV2lWkpk74URnUEhV28

###
GET http://localhost:3000/api/sponsors/athletes/noInvertibles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE2MTE5MCwiY3JlYXRlZF9hdCI6MTYzMjE1NzU5MCwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE1NzU5MH0.5Gwt4-SVPI09Kyoe3YpA7jfQXU8cjbBiKIB7UIdtDGo

###
GET http://localhost:3000/api/sponsors/athletes/countries
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE1NDMyMiwiY3JlYXRlZF9hdCI6MTYzMjE1MDcyMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE1MDcyMn0.49fdCbK2NwWcsLekEnZlTsImxV2lWkpk74URnUEhV28


###
GET http://localhost:3000/api/sponsors/athletes/sports
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE1NDMyMiwiY3JlYXRlZF9hdCI6MTYzMjE1MDcyMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE1MDcyMn0.49fdCbK2NwWcsLekEnZlTsImxV2lWkpk74URnUEhV28


### 
POST http://localhost:3000/api/sponsors/addSportFavorite/46
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NiwiZXhwaXJlZF9hdCI6MTYzMjM2MjgyMiwiY3JlYXRlZF9hdCI6MTYzMjM1OTIyMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjM1OTIyMn0.4tRuZCsITyu62PX2KquwKJZulGrS6Iffu-bVdwzaoKY
Content-Type: application/json

{
    "fk_sport": 5
    
}


### 
POST http://localhost:3000/api/users/resetPassword
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NiwiZXhwaXJlZF9hdCI6MTYzMjM2MjgyMiwiY3JlYXRlZF9hdCI6MTYzMjM1OTIyMiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjM1OTIyMn0.4tRuZCsITyu62PX2KquwKJZulGrS6Iffu-bVdwzaoKY
Content-Type: application/json

{
    "email": "adidas@gmail.com",
    "password": "Admin1234!"
    
}







### 
GET http://localhost:3000/api/sponsors/myathletes/49
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NiwiZXhwaXJlZF9hdCI6MTYzMjM2MjU1MiwiY3JlYXRlZF9hdCI6MTYzMjM1ODk1MiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjM1ODk1Mn0.X4fBhjTXQ7V88Q3o5FEpi3xYvm6mv-lpr66tvbUda78


### 
GET http://localhost:3000/api/sponsors/myAllOffers/51
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NSwiZXhwaXJlZF9hdCI6MTYzMjA2Mjg1OCwiY3JlYXRlZF9hdCI6MTYzMjA1OTI1OCwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjA1OTI1OH0.VGM2WyFgin7VXhidOpHEFcSVT5wno1iVA6iXx_yN5Z4

### 
GET http://localhost:3000/api/sponsors/myOffersRejecteds/1
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmVkX2F0IjoxNjMxNjQyMjMxLCJjcmVhdGVkX2F0IjoxNjMxNjM4NjMxLCJpYXQiOjE2MzE2Mzg2MzF9.6DccrZ8RsKlB6z-Mve6FJSeORt5aH0x1YC9cRCCYYSE

###
PUT http://localhost:3000/api/athletes/deleteaccount/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE3OTI3OSwiY3JlYXRlZF9hdCI6MTYzMjE3NTY3OSwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE3NTY3OX0.FJUPqoE-yVJQFupjLg4Z_A4Ywo-9VM4nLnTr_CaPxXc

###
GET http://localhost:3000/api/sponsors/49
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0OSwiZXhwaXJlZF9hdCI6MTYzMjEyOTY4MiwiY3JlYXRlZF9hdCI6MTYzMjEyNjA4MiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjEyNjA4Mn0.g7CGdk1ONd-EkicgolwvmClBObC_MiA6VcY2e1U3htc


### 
GET http://localhost:3000/api/sponsors/offer/2
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMSwiZXhwaXJlZF9hdCI6MTYzMTg3NjY5MiwiY3JlYXRlZF9hdCI6MTYzMTg3MzA5MiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMTg3MzA5Mn0.kTIp5ysEqvO1ep1egN3-Nqp3SjAuW-Gx9p0Id9wr_Wg


###
POST http://localhost:3000/api/sponsors/newOffer/46
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NSwiZXhwaXJlZF9hdCI6MTYzMjA4MTU1MiwiY3JlYXRlZF9hdCI6MTYzMjA3Nzk1MiwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjA3Nzk1Mn0.iFL3MfUvaqCIZ55POgcsBvzZNhDbofweXzM0BrOGGIQ
Content-Type: application/json

{
    "fk_sponsors": "2",
    "participations": "1888800"
}

###
PUT http://localhost:3000/api/sponsors/profile/45
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo0NSwiZXhwaXJlZF9hdCI6MTYzMjAwMzEyMywiY3JlYXRlZF9hdCI6MTYzMTk5OTUyMywidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMTk5OTUyM30.eNWzXMqD-bNa4f4YwkEQCl5Jbk--IvUTjVNkYACJJ9E
Content-Type: application/json

{
    "company": "tipitentito",
    "logo": "AHSUHAU", 
    "email": "tipitent@gmail.com"
}



###
PUT http://localhost:3000/api/sponsors/deleteAccount/52
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE3OTI3OSwiY3JlYXRlZF9hdCI6MTYzMjE3NTY3OSwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE3NTY3OX0.FJUPqoE-yVJQFupjLg4Z_A4Ywo-9VM4nLnTr_CaPxXc


###
POST http://localhost:3000/api/sponsors/addAthleteFavorite/49
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE3OTQwNywiY3JlYXRlZF9hdCI6MTYzMjE3NTgwNywidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE3NTgwN30.kmd1ZcZE_5vWnCiZEOifa6DTY8ofSOHQkGmmCIOlkCo

{
    "fk_sponsors": 51
}


###
PUT http://localhost:3000/api/sponsors/removeAthleteFavorite/49
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjE3OTQwNywiY3JlYXRlZF9hdCI6MTYzMjE3NTgwNywidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjE3NTgwN30.kmd1ZcZE_5vWnCiZEOifa6DTY8ofSOHQkGmmCIOlkCo

{
    "fk_sponsors": 51
}



###
GET http://localhost:3000/api/sponsors/sportsSponsors
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjIzMTUxMSwiY3JlYXRlZF9hdCI6MTYzMjIyNzkxMSwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjIyNzkxMX0.XLLD35pRQA_BGLxkmLFXjHJNdGQgZQ4T-RdD9k3FLeE


###
GET http://localhost:3000/api/sponsors/sportsBySponsor/53
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MywiZXhwaXJlZF9hdCI6MTYzMjMwNDEwOCwiY3JlYXRlZF9hdCI6MTYzMjMwMDUwOCwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjMwMDUwOH0.DrUeun23ykv5fjLoNBRoPR_M4N2zjyqARH0Qv_-w660


###
POST http://localhost:3000/api/sponsors/addSportFavorite/51
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjIzNjA0OSwiY3JlYXRlZF9hdCI6MTYzMjIzMjQ0OSwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjIzMjQ0OX0.EayECiY3c8zcPMhEtKJz9xty_UC_j-gmI2D1do9TimQ

{
    "fk_sport": "6"
}



###
POST http://localhost:3000/api/sponsors/send-email
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1MiwiZXhwaXJlZF9hdCI6MTYzMjIyMTE2MSwiY3JlYXRlZF9hdCI6MTYzMjIxNzU2MSwidXNlcl9yb2xlIjoiUyIsImlhdCI6MTYzMjIxNzU2MX0.sMCE-Y9OzLhOSnqWkblI_DiwlUbXK3f35e8RyxcTBH4






# ### 
# POST http://localhost:3000/api/users/register
# Content-Type: application/json

# {
#     "email": "rosittal@gmail.com",
#     "password": "aY9*",
#     "fk_athlete": 2,
#     "fk_sponsor": null,
#     "name": "Mar",
#     "surname": "Jilg",
#     "age": 20,
#     "photo": "aksjdjas",
#     "sport": "jaskjhdas",
#     "country": "asjhuasd",
#     "quantitydemand": "jasijdas",
#     "percentage": 40,
#     "limitdate": "2021-10-09",
#     "graphic": "askjdhajshdajs",
#     "followers": 219,
#     "company": null,
#     "logo": null
# }



# ### 
# POST http://localhost:3000/api/users/register
# Content-Type: application/json

# {
#     "email": "sponsorchuli@gmail.com",
#     "password": "Admin!24",
#     "fk_athlete": null,
#     "fk_sponsor": 19,
#     "name": null,
#     "surname": null,
#     "age": null,
#     "photo": null,
#     "sport": null,
#     "country": null,
#     "quantitydemand": null,
#     "percentage": null,
#     "limitdate": null,
#     "graphic": null,
#     "followers": null,
#     "company": "Importante",
#     "logo": "jaskjahsudsomoslosmejores"
# }